#+BRAIN_PARENTS: Foods

#+LATEX_HEADER: \usepackage{apacite}
#+OPTIONS: toc:nil num:nil 
* COMMENT Learning Goals -- The student exemplify the following:
** To understand geographical aspects of different countries
** To understand the costs associated with traveling to different countries
** To understand the cultural habits and traditions of a particular culture
** To utilize a variety of research and inquiry methods to gather data
** To create a works cited page 
* COMMENT Success Criteria -- The student will be successful when
** They have fully completed the /Trip Planner/
** They are able to collect, organize, and analyze relevant information from a variety of sources while managing the use of resources
** They have completed a works cited page
** They demonstrated an understanding of cultural habits, food, and traditions
* COMMENT Your Task
** You are a *Travel Agent*. Ms Baber is thinking about planning a trip to an international destination for the March Break March 9th to 18th. I am interested in immersing myself in the culture -- trying local foods, celebrating a local event, experiencing the climate/weather, and getting to know the habits of the people, etc. You are to choose from any of the destinations we explored in class this year.
** You *must research your destination*. Use the /Trip Planner/ to help you decide what information you have to research. You may also use your notes from class and your own knowledge to complete the task. You will have at 3 days this week to do your research. It is *DUE* June 22nd, 2017
** You must complete all the information in the /Trip Planner/ and submit in any format you would like. Ex. PowerPoint, Work Document, Travel Pamphlets, Photobook, etc.
* Trip Planner
** Name of destination
   Berlin, Germany
** Destination information: Write a few introductory paragraphs about the destination you are sending the client to. In other words, SELL ME, tell them what types of things to expect
   Berlin is a beautiful city, with bustling nightlife and never a dull moment. With many different; museums, restaurants, parks, concert halls and beer, it's hard to go wrong wherever you go during your trip. There's no real dress code in Berlin, if it's hot wear flip flops and shorts if you want to. If it's cold, bundle up with a heavy jacket. 
** What would the slogan be for this destination?
   "Du bist verrukt mein kind, du must nach Berlin"
** Travel Requirements
*** Medical
    Make sure your vaccinations are up to date
*** Passports
    Valid Canadian Passport
*** Visa
    Not required for visits up to 90 days.
*** Insurance
    Travel Health Insurance is recommended but not required
** Flight Information
*** Flight Date
    Fri, Mar 9
*** Return Flight
    Sun, Mar 18
*** Length of Flight
    14 hours and 15 minutes
*** Layovers
    1h 15m in Toronto, 3h 15m in Frankfurt.
*** Airlines
    Air Canada until Frankfurt, Lufthansa from Frankfurt to Berlin.
*** Cost w/ tax
    $1,532
** Geographical Information
*** Climate
    Average daily temperature of around 4C
*** Season
    Spring
*** Weather
    Approx. 36 mm of rainfall average in the month of march.
*** Geographical qualities
    Mainly flat, low-lying marshy woodlands. 
** Where will the client stay?
   ibis Hotel Berlin Mitte
*** Cost
    $926 for all 9 nights.
** Where would be a place to go eat a cultural meal?
   A good place to go for a cultural meal would be Marjellchen, a highly rated restaurant located at Mommsenstraße 9, 10629 Berlin, Germany. 
*** Menu Items
    http://www.marjellchen-berlin.de/
*** Cost for both currencies
    What you would expect from a restaurant.
** Local event happening at time of client's trip
   International Travel Trade Show - 7-11 March 2018\\
   MaerzMusik - 16-25 March 2018\\
   https://www.berlin.de/en/events/march/
*** What does event suggest about culture
    Seeing as the Travel Trade show is the largest in the world, I would say that they have a fairly diverse culture.
** Habits of the people
    - Recycling everything
    - No small talk
    - Carrying Cash
    - Getting angry at late public transport
      http://blackgirlinberlin.com/home/6-habits-i-picked-up-living-in-berlin/
