#+BRAIN_PARENTS: Entrepreneurship
#+TITLE: Ideas and the Creative Edge
#+AUTHOR: Kadin Buckton

* Ideas and the Creative Edge

Every venture starts with an idea -- but where does the idea come from?

Entrepreneurial and Enterprising people are always on the alert!

Whenever they meet someone new, open a newspaper or magazine, watch television or surf the internet!

* Good ideas have common features
  Good ideas come in many forms, but the ones that turn into ventures have two features in common:
  1) They are innovative -- often offering something that no one has thought of before
  2) They suggest a way to satisfy a need

* Ways to find NEW ideas
  - Online news
  - Trade magazine
  - Trade show
  
* Looking for patterns
** Watch for change
   - If the price of a popular item just increased, there might be room for a competitor to step in.
   - If people are beginning to buy a new product or service, there might be related products or services they would also be interested in buying
   - It is a great idea to start an ideas journal
* Developing your ideas
  *NOT ALL GOOD IDEAS MAKE GOOD VENTURES!!!!*
  - Once you find an idea that interests you, the research begins
  - Talk to people! Who will your customers be? What problems might you encounter?
  - Scrub daddy
