#+BRAIN_PARENTS: Entrepreneurship

#+TITLE: Impact on the Local Economy
#+AUTHOR: Kadin Buckton

Entrepreneurs have a powerful impact on the local economy

* Job Creation
  - When entrepreneurship creates jobs it has a multiplier effect
  - Those who are employed by the business have money to buy goods and services. If these goods/services are provided in the local community people will likely spend their money there and more jobs will be created.
  - (Walmart)
  
* New Ideas 
  - Entrepreneurship encourages the creation of a broader range of goods and services than would exist otherwise.
  - Many of us now take innovations such as the Internet, cell phones, IPODS or microwave ovens for granted!
  
* Economic Benefits
  - Through competition, entrepreneurs not only help lower prices but also improve societies standard of living
  - The success of a new venture can produce investment opportunities which in turn bring more wealth
  
* Political Benefits
  Entrepreneurship is strong in countries where:
  - Financial and legal institutions provide a strong foundation
  - Where money for starting a new venture is easily accessible
  - Where educations and training are widely available
  - Where laws do not deter new venture creation
