#+BRAIN_PARENTS: English
#+OPTIONS: toc:nil num:nil todo:nil

* DONE Introduce Yourself
  CLOSED: [2017-09-08 Fri 08:31] DEADLINE: <2017-09-08 Fri>

   My name is Kadin Christopher Buckton, Christopher being my father's name. Kadin, in Arabic, means "Companion". 

   I was born on September 14th, 2000, at 7:32 pm in London, Ontario. I also happened to be born 2 months early, needing a tube and a few weeks in the hospital. Fortunately, to my knowledge, this hasn't impeded my development or personality, which is a possibility with prematurely born babies. 

   My parents split up when I was around 1 year old, due to differences between them. I'm currently living with my mother, along with my stepfather, half-brother, two dogs and a cat. I still have a healthy relationship with both parents, visiting my father when he's in town. My mother's name is Krista Parker, and she works at Mapleview as a nurse. My stepfather's name is Jeremy Yourchuk, and he owns a contracting company with his sister called Andson contracting. My half-brother's name is Kyran Parker, and he happens to also go to Korah, currently in Grade 7. My father, Christopher Buckton, is married to my stepmother,  Louise Roy, and they have 3 beautiful children together. Their names are; Noah, Nathan and Nolan, being 12, 10, and 8 years old respectively. They also have three dogs, two bearded dragons, two Axolotls and a turtle.

   One of the people that keep me sane is my Girlfriend. Her name is Lili, and she's 17 years old. She currently lives in Gaylord, MI and we have been dating for three years. Some of her interests are; Art, Beauty and Writing.
   
   One of my passions when the urge hits, is writing Fiction. Recently, I've started writing a book about two scientists researching new flora and fauna on an alien planet, similar to Mars. I haven't worked on it much recently, but I plan to finish at least a few chapters by the end of the semester.

   Another one of my biggest passions in life is computers. Whether it be Programming, Systems Administration, IT, I love to do it. I find that I'm more productive using the computer to type things rather than writing, and can get things done quicker while better keeping track of tasks and deadlines. 

   I do a few extracurricular activities, mostly Hockey. I've been to the NOHA and OHF tournaments, placing first at the NOHA tournament, and coming just shy of placing at the OHF tournament.
