#+BRAIN_PARENTS: English Poetry

#+TITLE: Questions on "To his Coy Mistress"
#+AUTHOR: Kadin Buckton
#+DATE: <2017-09-20 Wed>

* Questions

1) A man trying to seduce a woman into sleeping with him.
2) How is this poem structured? Reduce each section to a single word that sums up what the narrator is saying.
   3 sections. Flatter, Coerce,  
3) 
4) What is the likelihood of finding rubies by the Ganges, or having all the Jews convert to Christianity? Why does the narrator bring up these ideas?
   The likelihood is basically impossible, and the narrator brings these ideas up to reiterate on how much he loves her, that he would love her until there are rubies by the Ganges / all the Jews convert to Christianity. This basically equates to the end of time.
5) 
6) 
7) What does he mean by "the last age should show your heart"?
   When the corpse is decomposing(?)
8) 
9) 
10) 
11) 
12) 
13) Her quaint honor turns to dust, and into ashes all his lust. Allusion?
    Ashes to Ashes, Dust to Dust, from the 1662 version of "The Book of Common Prayer"
14) 
15) 
16) 
17) Who is the narrator referring to when he says "his" slow chapped power?
    God
18) 
19) 
20) 
