#+BRAIN_PARENTS: Books

* Plant Sci-Fi

Planet 16732 -- Year 3041 -- Lunar Cycle 21

14:00

"This is Echo 1 to control, copy." His voice was dotted with static over the planet's comms system.
"Echo 1 this is control, we copy, over." Came the reply from control, the central command center on this planet.
"Control, we have succesfully found the crevace indicated on our mission statement. Permission to proceed, over."
"Permission granted Echo 1. Be careful down there. Out." With a soft click, the comms connection between control and Echo 1 was severed. He shuddered nervously.
"Feeling nervous?" Came a smooth voice over his private comms channel. He looked to his left, seeing his partner, Echo 2, looking rather nice in her Planetary Exploration Hazmat and Survival Suit. No one ever called it that though, it was always called the KMS. Standing both for what it did, Keeps Me Safe, and what you would be doing if you took it off, Killing My Self.
"Not at all" he shot back, obviously nervous. "We should get going, we're burning daylight here"
"The day are 865 years long, we could stand here until we die and it would still be daylight." She scoffed at him, shooting him a smirk. "But if you insist, we can get moving. Have the mission statement?"
"Locate and analyze new species of flora in the newly discovered crevace on this planet." He read off his HUD, for the 20th time in the last 10 minutes. Not that she knew that.
"Sounds easy enough, let's go." and she clipped onto the safety tether and began descending into the dark embrace of the crevace, smiling to herself as she listened to Echo 1 muttering to himself about it being easy, and following her.

14:32

"I believe I found something." Echo 1 stated, both through his private comms and to his onboard journal.
"What is it?" Echo 2 asked, walking over from where she was searching, looking to see what he was talking about.
"It looks like some sort of vine." He looked it over, noting the smoothness of the vine along with the pattern of spots perfectly placed along it.
"Looks weird." she said, a hint of displeasure leaking into her voice.
"I think it looks beautiful." he shot back, grinning. Suddenly, he froze.
Echo 2 looked back over to the vine, and was shocked to see it slowly moving, curling around her partners arm. "Do you want me to..." she trailed off as she thought about what she could do.
"No, leave it." he sighed. "It doesn't hurt and it doesn't seem like it's trying to eat me. Besides, it's our job to see what it does." His voice was nervous, but he was smiling at the vine, now curled fully around his arm, resting there like a sleeve. He looked over at Echo 2, noting her face looked a little pale.
"Yeah, sounds good to me." She said, looking like it didn't sound good to her.
"It'll be fine. Let's keep looking." he said firmly, and went back to looking for more new species.

15:09

"Is it me or does this crevace have nothing else in it." Echo 1 muttered. Ever since they found that vine, they haven't been able to find any more species of anything.
"I'm kinda glad, honestly." Echo 2 replied, still on the hunt for a sign of anything.
"Same, but it feels like there have been things here before." he sighed.
"Well, we'll just keep looking I suppose." she said, also sighing. Secretly, she was glad they hadn't found anything more. She kept stealing glances towards the vine wrapped around her partners arm. It almost seemed to be laughing at her.
"I'm going to go look over there." he motioned towards a darker area, deeper in the crevice.

15:37

"2, come look at this!" Echo 1 said excitedly to his partner, Echo 2, over the comms. He switched on his Journal. "I appear to have found an opening, covered by a large rock. We are going to move it and see what is in the opening."
 
