#+BRAIN_PARENTS: Poetry
#+OPTIONS: toc:nil num:nil ':true todo:nil
#+TITLE: How Relevant is the Continued Study
#+TITLE: of Serious Literature to Education and or Society
#+AUTHOR: Kadin Buckton
#+DATE: September 12, 2017

# 500-650 words
   
  I believe that the study of serious literature is still very relevant to both education and society, giving us the ability to pull different topics from books, old and new, that are still relevant topics in society today. 
  
  With the advancements of technology, people in general have many more avenues available to them to consume content, whether it be messaging, blogs, games, etc. Traditionally, books were one of only a handful of available things for society to consume, and so reading was a lot more prevalent. Nowadays, while reading books is still very common in my experience, it is easier for someone to skim a blog than to open up a book. I don't think this is necessarily a bad thing, maybe it's a blog about Euphemisms in books, but I do think that everyone can better themselves at least a little bit by reading a good book every now and then.
  
  I think that it's okay that Hollywood makes "mediocre" movies from books, the quality of the movies are subjective, and some people enjoy watching things more than reading things. I've personally enjoyed some movie adaptations of books just as much as the books itself, such as the Percy Jackson books and The Mortal Instruments. I believe that a big contributing factor in a movie being worse than the book is that when you're reading a book, you have the full function of your imagination to visualize the scene in the detail that you want, whereas in a movie you only have what the director has decided to include in the shot.
  
  In my opinion, the current approach to teaching literature in school is the correct one. It is much easier, at least for me, to pick up a book and read it cover to cover once and then go back to it and read it again, looking for symbolism, archetypes, metaphors etc. I also find it much easier to discuss different literary devices of a book in a group, and being able to hear what someone else found that you might not have noticed when you read through the book.

  Another thing that I believe to be purely opinion is "confectionery" literature vs "serious" literature. While I may not personally get any deep meaning out of the Twilight series, it doesn't mean that someone else wont. Just because a book might not have been written with certain symbolisms in mind, it doesn't mean that the symbolism isn't present, and with a little effort be identified and examined.

  I believe that ease of access to online resources that sum up and / or dumb down books is actually helpful in the correct circumstances. Obviously if you don't actually read the book and just read the overview of it you aren't going to be getting the required information. However I think it's beneficial to read an overview of a book before you actually read it, and make it a point to look for and mark down where certain symbols or archetypes are presented, and decide for yourself what it means.
  
  
  
