#+BRAIN_PARENTS: Homework

#+TITLE: Chapter 6 Questions
#+AUTHOR: Kadin Buckton
#+OPTIONS: toc:nil num:nil
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

* Why are proactive people likely to make a better choice? Explain.

Proactive people anticipate future decisions or problems and take action. They don't ignore a problem, hoping that it will go away. They act as soon as they realize something needs to be done, and they don't let fear of making a wrong decision stand in their way.

* How does having a positive attitude help you make decisions?

With a positive attitude, you can often see more options. Keeping an optimistic outlook can help you approach decisions and problems as interesting challenges and learning experiences.

* Give an example of how peer pressure can be a positive or negative influence

Peer pressure can be positive because you're getting support from people, but it could also be a negative influence because you are always personally responsible for the choices you make.

* What types of information does the media present?

Facts, fiction, and opinions. Most of the information is intended to influence your thinking and your choices.

* What aspects of society and culture influence your choices?

Cultural traditions, religious beliefs, societal expectations and current trends.

* What does the word consequences refer to?

It refers to the result of your decisions.

* Why is it helpful to identify the decision you are making before you begin weighing your choices?

It helps you decide how much thought you should put into the decision.

* What should a person consider when evaluating possible options?

The impact it has on other people.

* Give an example of a practical problem a teen might have.

Learning to play an instrument, or doing too many chores around the house.

* What other people may be affected by a practical problem?

Friends, family, classmates and members of the community.

* What does context mean?

Context refers to all of the conditions surrounding the problem or situation. 

* Summarize the 4 steps to consider when making an ethical decision

** Context

   Figure out what's at play and who the decision is going to affect
   
** Desired Ends

   What has to happen in order for everyone involved to feel that the problem is solved?

** Means

   How am I going to reach my desired ends?
   
** Consequences

   What are the results of this decision going to be?

* What is the difference between practical reasoning and decision making?

  Practical reasoning isn't a step by step process, instead you are likely to move back and forth among the four aspects.

* Summarize the REASON process

** R

   Figure out what the /main/ problem is

** E

   What information do I need to solve the problem?
   
** A

   Are there any alternatives? What consequences are going to result from my decisions?

** S

   Figure out what the best option is
   
** O

   Create a step by step plan on how to solve the problem
   
** N

   Note the outcome of your decision, and see if it had positive or negative results, and figure out how you can do better next time
