#+BRAIN_PARENTS: English Poetry

#+TITLE: Porphyria's Lover Questions
#+AUTHOR: Kadin Buckton

1) 
   a) A poem in the form of a speech or narrative by an imagined person, in which the speaker inadvertently reveals aspects of their character while describing a particular situation or series of events.
   b) Telling us the story of what happened, tells us details of the fling
2) The narrator is Porphyria's Lover. His mental state isn't very good, he kills Porphyria to freeze everything in time.
3) Porphyria is in a higher class socially, which is the reason they can't be together. This helps understand the poem, because we can see a motive behind why Porphyria can't be with him.
4) "Passion sometimes would prevail"
5) Can't stay because of social class
6) Yellow hair -- Sunshine, warm, caring
7) 
8) "And yet God has not said a word!" -- Believes that what he did was right.
9) 
   - Guy loving then killing girl
   - Guys are mentally unstable
   - Both killers were story's narrator
   - "Trophy" of women
   - No regrets
