#+BRAIN_PARENTS: Math

#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+OPTIONS: toc:nil num:nil
\setlength{\parindent}{0pt}
* Note

  In mathematics, you must be able to represent intervals and identify smaller sections of a relation or a set of numbers.

  You have used the following inequality symbols:

  > greater than\\
  < less than\\
  \(\geq\) greater than or equal to\\
  \(\le\) less than or equal to

  Linear Inequality is an inequality that contains an algebraic expression of degree 1

  For example:

  \(5x+3 \le 6x-2\)
  
  We solve inequality much the same as we do equations.

** Ex. 1 - Solve an Inequality

   Solve for all values of x.

   \(4x+3 \geq 15\)\\
   \(4x \geq 15-3\)\\
   \(4x \geq 12\)\\
   \(\frac{4x}{4} \geq \frac{12}{4}\)\\
   \(x \geq 3\)

   We can also write out solution using set notation.

   \(\{x\in \mathbb{R} \mid x \geq 3\}\)\\
   \(x\in[3,\infty)\)\\

   Solve for all values of x.

   \(7-3x\le-2\)\\
   \(-3x\le-2-7\)\\
   \(-3x\le-9\)\\
   \(\frac{-3x}{-3}\le\frac{-9}{-3}\)\\
   \(x\geq3\)

   When dividing or multiplying by a negative constant, we need to reverse the inequality sign

   \(\{x \in \mathbb{R} \mid x \geq 3\}\)\\
   \(x \in [3, \infty)\)

** Ex. 3 - Solving a Double Inequality

Solve for all values of x

\(30 \le 3(2x+4)-2(x+1) \le 46\)\\
\(30 \le 6x+12-2x-2 \le 46\)\\
\(30 \le 4x+10 \le 46\)\\
\(30-10 \le 4x+10-10 \le 46-10\)\\
\(20 \le 4x \le 36\)\\
\(\frac{20}{4} \le \frac{4x}{4} \le \frac{36}{4}\)\\
\(5 \le x \le 9\)
