#+BRAIN_PARENTS: Entrepreneurship

#+TITLE: Young Entrepreneurship
#+AUTHOR: Kadin Buckton

* Facts
  - Nearly one third of 18-35 year-olds rated entrepreneurship as the more desirable profession
    32 percent

* Challenges
  - The greatest challenge facing a young entrepreneur is the lack of experience and knowledge they bring to a venture
  - Young entrepreneurs typically have no credit history, no collateral and no track record of paying off a debt
  
* The Value of Experience
  - Part time and summer work, volunteer opportunities, and school leadership positions offer young people opportunities to develop their enterprising and entrepreneur skills.
  
  Working part-time or full-time can provide great opportunities such as:
  - Learn about the infrastructure
  - Develop a positive reputation in t he industry
  - Build a network of contacts
  - Earn money you can save for the future
  - Learn firsthand about the industry
  
* Strategies for Entrepreneurship Success
  - Think First
    Planning is crucial! Remember that reflective decisions are typically better than impulsive ones.
  - Believe in Yourself
    Improve your own performance rather than competing with others
  - Know Yourself
    When planning your venture, take time to consider your own abilities, character traits, skills and goals.
  - Enjoy the Challenge
    To be worth your time and effort, a venture should challenge your abilities, encourage your creativity, suit your personality, and be compatible with the vision of yourself
